/*!
 * GameSocket.js v1.0.0
 * Copyright (c) 2023 by 小宏XeLa
 * Licensed under MIT
 */
!function(){var g=g||{};g.scope={};g.arrayIteratorImpl=function(b){var h=0;return function(){return h<b.length?{done:!1,value:b[h++]}:{done:!0}}};g.arrayIterator=function(b){return{next:g.arrayIteratorImpl(b)}};g.makeIterator=function(b){var h="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if(h)return h.call(b);if("number"==typeof b.length)return g.arrayIterator(b);throw Error(String(b)+" is not an iterable or ArrayLike");};!function(b,h){"undefined"!==typeof module?module.exports=
h():(b||globalThis).GameSocket=h()}(this,function(){if(!GameStorage)throw Error("GameSocket runtime requires GameStorage.");var b=storage;if(!b)throw Error("GameSocket runtime requires GameStorage.");var h=b.getGroupStorage;if(!h)throw Error("GameSocket runtime requires GameStorage.");b=function(f){var a=this;this.readyState=0;this._db=h("GAMESOCKET_DBNAME_"+f);this._processed=[];this._closed=!1;this._callback=[];var l=Date.now(),k=function(){a._db.list({pageSize:999999999999,cursor:1}).then(function(e){if(2==
a.readyState)a.readyState=3;else{if(0==a.readyState){a.readyState=1;for(var c=g.makeIterator(a._callback.filter(function(n){return"open"==n.name})),d=c.next();!d.done;d=c.next())d.value.callback({startTimestamp:Number(l),endTimestamp:Number(Date.now())})}d=e.getCurrentPage();e=g.makeIterator(d);for(d=e.next();!d.done;d=e.next())if(c=d.value,!1===a._processed.includes(c.key)){a._processed.push(c.key);var m=g.makeIterator(a._callback.filter(function(n){return"message"==n.name}));for(d=m.next();!d.done;d=
m.next())d.value.callback({data:c.value,sendTimestamp:Number(c.key),acceptTimestamp:Number(Date.now())})}setTimeout(function(){k()},16)}},function(e){a.readyState=2;var c=function(){if(3==a.readyState)for(var d=g.makeIterator(a._callback.filter(function(n){return"close"==n.name})),m=d.next();!m.done;m=d.next())m.value.callback({error:e,timestamp:Number(Date.now())});else setTimeout(c,16)};c()})};k()};b.prototype.onMessage=function(f){var a={name:"message",callback:f};this._callback.push(a);return{cancel:function(){a.name=
"";a.callback=function(){}}}};b.prototype.onOpen=function(f){var a={name:"open",callback:f};this._callback.push(a);return{cancel:function(){a.name="";a.callback=function(){}}}};b.prototype.onClose=function(f){var a={name:"close",callback:f};this._callback.push(a);return{cancel:function(){a.name="";a.callback=function(){}}}};b.prototype.send=function(f){var a=this;return new Promise(function(l,k){var e=String(Date.now());a._processed.push(e);a._db.set(e,f).then(function(){l();var c=function(){a._db.remove(e).catch(function(){c()})};
setTimeout(function(){c()},2500)},function(c){k(c)})})};b.prototype.close=function(){var f=this;return new Promise(function(a){f.readyState=2;var l=function(){if(3==f.readyState){a(!0);for(var k=g.makeIterator(f._callback.filter(function(c){return"close"==c.name})),e=k.next();!e.done;e=k.next())e.value.callback({error:Error("GameSocket was manually disconnected."),timestamp:Number(Date.now())})}else setTimeout(l,16)};l()})};b.version="1.0.0";Object.assign(b,{CONNECTING:0,OPEN:1,CLOSING:2,CLOSED:3});
return b})}();
